### ISSUE TITLE
beat doesn't log when `None` was returned.

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#101]
I noticed that questions -- that uses a beat -- which could return `None` as a value do not get logged. 

Here is what gets logged:
```
Actor examines thing
... hoping it's equal to <None>
    => <None>
```

Here is what I would expect to get logged:
```
Actor examines thing
    => <None>
... hoping it's equal to <None>
    => <None>
```

**Comment by bandophahita** [comment]
And in case it was not obvious (it wasn't to me) the reason the resolution got logged in this case was because of the way hamcrest deals with logged values.  `None` is wrapped in the `IsEqual` object.  When we do a `is not None` check it passes because the object isn't `None`.  Those clever folks at hamcrest...
```python
                if retval is not None:
                    aside(f"=> {represent_prop(retval)}")
```

**Comment by perrygoy** [comment]
i think we can probably do something like:
```python
if retval is not None or isinstance(func, Answerable):
    ...
```

or maybe keep a log of which protocols will be expected to return useful information from their -able method.

**Comment by bandophahita** [comment]
Unfortunately `func` isn't an instance of the protocols, it's `function`.  We might have to get creative on how we identify which functions are allowed to return None.
