### ISSUE TITLE
project standardizations

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#127]
Going through each screenpy package (base, selenium, requests, etc) I've noticed we (mostly myself) haven't done a good job of keeping portions of the projects synchronized. 

case in point:
screenpy pyproject.toml has this section at the bottom of the file
https://github.com/ScreenPyHQ/screenpy/blob/1c8a8b22ff574a99a0a9f54892a13384e432bfc8/pyproject.toml#L224-L226

while screenpy_selenium has it somewhere in the middle:
https://github.com/ScreenPyHQ/screenpy_selenium/blob/dd85ed212bc8f2a52d35591795b45fc9eea5d544/pyproject.toml#L102-L108

As configurations changes are made across all projects, it would be advantageous if the portions of these projects matched (as much as they are able).

Files for consideration:

- .pre-commit-config
- pyproject.toml
- Makefile
- mypy.ini
- tox.ini
- gh actions

**Comment by perrygoy** [comment]
On our huddle just now you mentioned also adding a test to check the copyright for the current year, i like that!

**Comment by perrygoy** [comment]
Projects standardized; success!
