### ISSUE TITLE
perform_as function not being called or reached

### ISSUE THREAD

**Issue by tomknee-accelins** [ScreenPyHQ/screenpy#146]
I have a test like so...

```python
given(actor).was_able_to(StartThePreprocessService.with_dependencies(kafka_client["bootstrap_servers"], s3_client))
```

and the task is like this...

```python
from screenpy import Actor
from screenpy.pacing import beat

from utils.s3_client import S3Client
from tests.integration.src.screenplay.abilities.run_the_preprocess_service import RunThePreprocessService


class StartThePreprocessService:
    """
    Task for an actor to Start the main process of the Preprocess service.

    Example::
        the_actor.attempts_to(StartThePreprocessService.with_dependencies(kafka_bootstrap_server, s3_client))
    """
    @staticmethod
    def with_dependencies(kafka_bootstrap_server: str, s3_client: S3Client) -> "StartThePreprocessService":
        return StartThePreprocessService(kafka_bootstrap_server, s3_client)

    @beat("{} has started the main process of the Preprocess service")
    def perform_as(self, the_actor: Actor) -> None:
        the_actor.ability_to(RunThePreprocessService).run_main_process(self.kafka_bootstrap_server, self.s3_client)

    def __init__(self, kafka_bootstrap_server: str, s3_client: S3Client) -> None:
        self.kafka_bootstrap_server = kafka_bootstrap_server
        self.s3_client = s3_client

```

When I add breakpoints and debug, I see the static method is reached and the init method is also reached, but the `perform_as` function is never reached?? What am I missing?

**Comment by tomknee-accelins** [comment]
Issue was when I had test annotated with patch hmm

**Comment by perrygoy** [comment]
I can't tell you the number of times i submit a bug only to realize the problem was my own fault immediately after i clicked send.

I'm glad it was an easy one! :D

*Edit: (Well, an easy one to fix, if not an easy one to spot. :P)*

**Comment by tomknee-accelins** [comment]
So for transparency, I added a patch annotation from unittest.mock above my test function and that prevented perform_as from being reached.

**Comment by perrygoy** [comment]
Oh, i'm actually interested to know more. I thought you had patched out your `perform_as` method, but it sounds like something else was happening—could you share your patched code?
