### ISSUE TITLE
Allow SeeAllOf and SeeAnyOf to accept only one test

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#32]
Per [discussion in discord](https://discord.com/channels/997223093040857119/997223093040857122/1024409614760038501),  `SeeAllOf` and `SeeAnyOf` should be allowed to accept a single tuple pair of question and resolution.

**Comment by bandophahita** [comment]
#31 addresses this

**Comment by perrygoy** [comment]
Merged!
