### ISSUE TITLE
Link to Screenplay Pattern video is broken

### ISSUE THREAD

**Issue by emanlove** [ScreenPyHQ/screenpy#4]
The [link](https://www.youtube.com/watch?v=8f8tdZBvAbI) to the screenplay video on the main index.rst page is broken as it leads to an account that has been deleted.

**Comment by perrygoy** [comment]
Oh no! It looks like that account is gone. I can't find anywhere else that video is hosted, either.

Thanks for calling this out @emanlove, i guess i'll link to Antony's original blog post instead. :(

**Comment by perrygoy** [comment]
Thanks again! I found a link to the [slides from the presentation](https://www.slideshare.net/RiverGlide/refactoring-page-objects-the-screenplay-pattern) instead, which is at least second-best. The docs have been updated to include that.
