### ISSUE TITLE
Allow shorter Actor `attempts_to`.

### ISSUE THREAD

**Issue by perrygoy** [ScreenPyHQ/screenpy#42]
We could support a shorter way of saying `attempts_to`. The first suggestion is adding a `tries_to` alias, but we could go even further by adding a `__call__` method to Actors. The latter would enable this:
```python
# using ScreenPy Selenium as an example
the_actor(
    Enters.the_text(USERNAME).into_the(USERNAME_FIELD),
    Enters.the_secret(PASSWORD).into_the(PASSWORD_FIELD),
    Clicks.on_the(LOGIN_BUTTON),
)
```

We'd just need to also add aliases for all the existing Actions to work with present tense.

**Comment by bandophahita** [comment]
A bunch of alias have been added in https://github.com/ScreenPyHQ/screenpy/pull/45.

Though, I like the idea of `__call__` on actors.

**Comment by perrygoy** [comment]
Actors can now be called (how thematic) and we've added present-tense aliases for all the Actions!
