### ISSUE TITLE
Github action to run `poetry check`

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#47]
`poetry check` verifies the toml and lock files are in sync.  This would catch any issues where the toml was updated but a new lock wasn't generated.

**Comment by perrygoy** [comment]
Would this also catch when a new lock *should* be generated (that is, a dependency was updated within the toml's specified ranges) but wasn't?

**Comment by bandophahita** [comment]
I believe so. AFAIK, when you run `poetry install` it performs `poetry check` first, which was how I was able to see that screenpy-allure was expecting screenpy >4.0.  Subsequently, when I tried to run `poetry lock` it too ran into the same issue until screenpy-allure reqs were updated.

By that nature, I figure if we simply run a check it should at least let us know there is a dependency problem.

**Comment by bandophahita** [comment]
Fixed in https://github.com/ScreenPyHQ/screenpy/pull/48
