### ISSUE TITLE
Create "Each"

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#79]
Consider this code:
```python
VISIBLE = (
    (Element(TARGET1), Visible()),
    (Element(TARGET2), Visible()),
)
admin.shall(Eventually(SeeAllOf(*VISIBLE)))
```

What if we had a determiner word to use instead?
```python
admin.shall(Eventually(SeeAllOf(Each(VISIBLE))))
```

**Comment by perrygoy** [comment]
I'm not sure how this would work... or if it would be clearer than the `*VISIBLE` approach.

Do you have an idea of how to implement this?

**Comment by bandophahita** [comment]
Yeah, I have no idea how that would be possible.  Must have been good drugs that day.
