### ISSUE TITLE
Add documentation examples of what gets printed in the logs

### ISSUE THREAD

**Issue by bandophahita** [ScreenPyHQ/screenpy#8]
Unless I'm blind, I don't think we have a single example of what the logging output will be for a given set of test examples.  It might be good to show users what they will be getting in some simple and complex tests.

**Comment by perrygoy** [comment]
That's a good call. We only have one example in the docs, and it's at the bottom of the Tasks page... and it didn't survive the formatting: https://screenpy-docs.readthedocs.io/en/latest/example/tasks.html

Now that the [screenpy_examples](https://github.com/ScreenPyHQ/screenpy_examples) repo is up, i think we can just pull some example logging from there!
