### ISSUE TITLE
Bad RST linkage on Silently

### ISSUE THREAD

**Issue by MarcelWilson** [ScreenPyHQ/screenpy#94]
I noticed the way `Silently` is displayed seems to be broken.
https://screenpy-docs.readthedocs.io/en/latest/cookbook.html#using-silently

<img width="696" alt="image" src="https://github.com/ScreenPyHQ/screenpy/assets/87030014/93a01a08-3daf-4dcb-8fcc-6ffe4d6eba52">

**Comment by perrygoy** [comment]
Sorry, i should have caught this one.

`Silently` isn't a function, it's a class, so it should be prefixed with `:class:` instead of `:function:`.

**Comment by MarcelWilson** [comment]
I thought so too, but technically it IS a function.
https://github.com/ScreenPyHQ/screenpy/blob/7882861f40946814293ea3ff8f2bca9a9c31494e/screenpy/actions/silently.py#L119

**Comment by perrygoy** [comment]
Oh that's right! I forgot that this one is a weird one. :P

Then i'm guessing it's because it's `:func:` not `:function:`?

**Comment by perrygoy** [comment]
This looks like it's been fixed, thanks @MarcelWilson!
